<?php

namespace Ais\IjasahSmaBundle\Repository;

/**
 * IjasahSmaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IjasahSmaRepository extends \Doctrine\ORM\EntityRepository
{
}
